/* ══════════════════════════════════════════════════════════════════════
   SHALOM VALLEY — CAMP DATA
   Generated by admin.html. You can hand-edit it, but it is easier and
   safer to open admin.html, make your changes, and download a new copy
   of this file.
   ══════════════════════════════════════════════════════════════════════ */
window.CAMPS = {

  "settings": {
    "endpoint": "",
    "contactPhone": "098 314 191",
    "contactEmail": "bookings@shalomvalley.org",
    "qrImage": "qr-code.png",
    "qrCaption": "ABA PAY / KHQR — Alongsiders Organization · Shalom Valley · 007 190 860",
    "rulesPdfEn": "camp-rules-en.pdf",
    "rulesPdfKm": "camp-rules-km.pdf"
  },

  "camps": [
    {
      "slug": "example-camp-2026",
      "status": "draft",
      "nameEn": "Example Youth Camp 2026",
      "nameKm": "ជំរុំយុវជនគំរូ ២០២៦",
      "taglineEn": "Four days of adventure, friendship and faith at Shalom Valley.",
      "taglineKm": "បួនថ្ងៃនៃការផ្សងព្រេង មិត្តភាព និងជំនឿនៅ Shalom Valley។",
      "datesEn": "12–15 December 2026",
      "datesKm": "១២–១៥ ធ្នូ ២០២៦",
      "locationEn": "Shalom Valley, Kep",
      "locationKm": "Shalom Valley, កែប",
      "agesEn": "Ages 12–18",
      "agesKm": "អាយុ ១២–១៨ ឆ្នាំ",
      "costEn": "US$60 per person",
      "costKm": "៦០ ដុល្លារ ក្នុងម្នាក់",
      "deadlineEn": "30 November 2026",
      "deadlineKm": "៣០ វិច្ឆិកា ២០២៦",
      "fees": [
        { "en": "Camper (per person)", "km": "អ្នកចូលរួមជំរុំ (ក្នុងម្នាក់)", "amount": "US$60" },
        { "en": "Leader (per person)",  "km": "អ្នកដឹកនាំ (ក្នុងម្នាក់)",   "amount": "US$45" },
        { "en": "Deposit to hold your place", "km": "ប្រាក់កក់ដើម្បីរក្សាកន្លែង", "amount": "US$20" }
      ]
    }
  ]
};
