/* ══════════════════════════════════════════════════════════════════════
   SHALOM VALLEY — CAMP DATA
   Generated by the camp manager. You can hand-edit it, but it is easier
   and safer to open the manager, make your changes, and save a new copy.

   NOTE: the three camps below are SAMPLES, made up to show how the cards
   and the form look. Replace them with your real camps.
   ══════════════════════════════════════════════════════════════════════ */
window.CAMPS = {

  "settings": {
    "endpoint": "",
    "contactPhone": "0316313339",
    "contactEmail": "bookings@shalomvalley.org",
    "qrImage": "qr-code.png",
    "qrCaption": "ABA PAY / KHQR — Alongsiders Organization · Shalom Valley · 007 190 860",
    "rulesPdfEn": "camp-rules-en.pdf",
    "rulesPdfKm": "camp-rules-km.pdf"
  },

  "camps": [

    {
      "slug": "youth-adventure-2026",
      "status": "open",
      "nameEn": "Youth Adventure Camp 2026",
      "nameKm": "ជំរុំផ្សងព្រេងយុវជន ២០២៦",
      "image": "img/poster-youth.svg",
      "accent": "#2F6B47",
      "accentDark": "#1E5C3A",
      "accentInk": "#245537",
      "badgeEn": "Few places left",
      "badgeKm": "នៅសល់កន្លែងតិច",
      "blurbEn": "Four days of ziplines, water challenges and campfires — built to stretch teenagers and grow friendships.",
      "blurbKm": "បួនថ្ងៃនៃការជិះខ្សែរអិល ការប្រកួតក្នុងទឹក និងភ្លើងជំរុំ — ធ្វើឡើងដើម្បីជំរុញយុវវ័យ និងបង្កើតមិត្តភាព។",
      "taglineEn": "Four days of adventure, friendship and faith in Kep.",
      "taglineKm": "បួនថ្ងៃនៃការផ្សងព្រេង មិត្តភាព និងជំនឿនៅកែប។",
      "purposeEn": "This camp is for teenagers who are ready to be stretched. Through the zipline, the water obstacle course and team challenges, campers meet things they think they cannot do — and find they can. Evenings around the fire give space to talk honestly about courage, friendship and faith, with leaders who listen more than they lecture.",
      "purposeKm": "ជំរុំនេះសម្រាប់យុវវ័យដែលត្រៀមខ្លួនទទួលការជំរុញ។ តាមរយៈខ្សែរអិល ផ្លូវឧបសគ្គក្នុងទឹក និងបញ្ហាប្រឈមជាក្រុម អ្នកចូលរួមជួបប្រទះនឹងអ្វីដែលពួកគេគិតថាធ្វើមិនបាន — ហើយរកឃើញថាពួកគេធ្វើបាន។ ពេលល្ងាចជុំវិញភ្លើង ផ្តល់ពេលវេលាដើម្បីនិយាយដោយស្មោះអំពីសេចក្តីក្លាហាន មិត្តភាព និងជំនឿ ជាមួយអ្នកដឹកនាំដែលស្តាប់ច្រើនជាងបង្រៀន។",
      "program": [
        { "whenEn": "Day 1 — Thu", "whenKm": "ថ្ងៃទី១ — ព្រហ", "whatEn": "Arrive and settle in, camp rules and teams, facilitated camp games, opening session and bonfire with s'mores.", "whatKm": "មកដល់ និងរៀបចំកន្លែងស្នាក់នៅ បទបញ្ជាជំរុំ និងបែងចែកក្រុម ល្បែងជំរុំ វគ្គបើក និងភ្លើងជំរុំជាមួយនំស្មរ។" },
        { "whenEn": "Day 2 — Fri", "whenKm": "ថ្ងៃទី២ — សុក្រ", "whatEn": "Zipline rotations, team initiatives, pool games in the afternoon, small groups in the evening.", "whatKm": "ជិះខ្សែរអិលតាមវេន សកម្មភាពក្រុម ល្បែងក្នុងអាងហែលទឹកពេលរសៀល ក្រុមតូចពេលល្ងាច។" },
        { "whenEn": "Day 3 — Sat", "whenKm": "ថ្ងៃទី៣ — សៅរ៍", "whatEn": "Water obstacle course, bomb crater history discussion, tree planting, bush dance after dinner.", "whatKm": "ផ្លូវឧបសគ្គក្នុងទឹក ការពិភាក្សាប្រវត្តិសាស្ត្រនៅរណ្តៅគ្រាប់បែក ការដាំដើមឈើ និងការរាំបន្ទាប់ពីអាហារពេលល្ងាច។" },
        { "whenEn": "Day 4 — Sun", "whenKm": "ថ្ងៃទី៤ — អាទិត្យ", "whatEn": "Morning worship, closing session and commitments, pack up, depart after lunch.", "whatKm": "ការគោរពប្រណិប័តន៍ពេលព្រឹក វគ្គបិទ និងការប្តេជ្ញា រៀបចំវ៉ាលី និងចាកចេញបន្ទាប់ពីអាហារថ្ងៃត្រង់។" }
      ],
      "includesEn": "The fee covers dorm accommodation, all meals from Thursday dinner to Sunday lunch, every activity listed above, and the full facilitated programme run by the Shalom Valley team. Transport to and from camp is arranged by your group.",
      "includesKm": "ថ្លៃសេវារួមបញ្ចូលកន្លែងស្នាក់នៅបន្ទប់រួម អាហារទាំងអស់ចាប់ពីអាហារល្ងាចថ្ងៃព្រហស្បតិ៍ ដល់អាហារថ្ងៃត្រង់ថ្ងៃអាទិត្យ សកម្មភាពទាំងអស់ខាងលើ និងកម្មវិធីពេញលេញដឹកនាំដោយក្រុមការងារ Shalom Valley។ ការធ្វើដំណើរទៅមកត្រូវរៀបចំដោយក្រុមរបស់អ្នក។",
      "datesEn": "10–13 December 2026",
      "datesKm": "១០–១៣ ធ្នូ ២០២៦",
      "locationEn": "Shalom Valley, Kep",
      "locationKm": "Shalom Valley, កែប",
      "agesEn": "Ages 13–17",
      "agesKm": "អាយុ ១៣–១៧ ឆ្នាំ",
      "costEn": "US$60 per camper",
      "costKm": "៦០ ដុល្លារ ក្នុងម្នាក់",
      "deadlineEn": "28 November 2026",
      "deadlineKm": "២៨ វិច្ឆិកា ២០២៦",
      "fees": [
        { "en": "Camper (per person, 3 nights)", "km": "អ្នកចូលរួមជំរុំ (ក្នុងម្នាក់ ៣យប់)", "amount": "US$60" },
        { "en": "Group leader (per person)", "km": "អ្នកដឹកនាំក្រុម (ក្នុងម្នាក់)", "amount": "US$45" },
        { "en": "Deposit to hold your places", "km": "ប្រាក់កក់ដើម្បីរក្សាកន្លែង", "amount": "US$20 each" },
        { "en": "Bus driver accommodation (optional)", "km": "កន្លែងស្នាក់នៅអ្នកបើកបរ (ស្រេចចិត្ត)", "amount": "US$14 per night" }
      ]
    },

    {
      "slug": "leaders-retreat-2027",
      "status": "open",
      "nameEn": "Leaders Rest & Renewal Retreat",
      "nameKm": "ការឈប់សម្រាក និងស្តារកម្លាំងសម្រាប់អ្នកដឹកនាំ",
      "image": "img/poster-leaders.svg",
      "accent": "#25506F",
      "accentDark": "#16304A",
      "accentInk": "#1B3F59",
      "badgeEn": "Adults only",
      "badgeKm": "សម្រាប់មនុស្សពេញវ័យ",
      "blurbEn": "Three unhurried days for youth workers and pastors. Slow mornings, honest conversation, no programme to run.",
      "blurbKm": "បីថ្ងៃដ៏ស្ងប់ស្ងាត់សម្រាប់អ្នកធ្វើការជាមួយយុវជន និងគ្រូគង្វាល។ ព្រឹកដ៏យឺតៗ ការសន្ទនាដោយស្មោះ គ្មានកម្មវិធីត្រូវដឹកនាំ។",
      "taglineEn": "Three days to put the load down.",
      "taglineKm": "បីថ្ងៃដើម្បីដាក់បន្ទុកចុះ។",
      "purposeEn": "People who look after everyone else rarely get looked after. This retreat exists to reverse that for three days. There is no early bell, no team you are responsible for, and nothing you have to organise. Meals are cooked for you, mornings are unstructured, and the two guided sessions are conversations rather than lectures. Come tired; that is the point.",
      "purposeKm": "អ្នកដែលមើលថែអ្នកដទៃ កម្រទទួលបានការមើលថែវិញណាស់។ ការឈប់សម្រាកនេះមានគោលបំណងផ្លាស់ប្តូរវាក្នុងរយៈពេលបីថ្ងៃ។ គ្មានកណ្តឹងដាស់ព្រឹកព្រលឹម គ្មានក្រុមដែលអ្នកត្រូវទទួលខុសត្រូវ និងគ្មានអ្វីដែលអ្នកត្រូវរៀបចំ។ អាហារត្រូវបានចម្អិនជូនអ្នក ពេលព្រឹកគ្មានកាលវិភាគ ហើយវគ្គណែនាំពីរគឺជាការសន្ទនា មិនមែនការបង្រៀនទេ។ សូមមកទាំងអស់កម្លាំង — នោះជាគោលបំណង។",
      "program": [
        { "whenEn": "Friday", "whenKm": "ថ្ងៃសុក្រ", "whatEn": "Arrive from 2pm. Coffee on the deck, no agenda. Dinner together, then an opening evening around the fire.", "whatKm": "មកដល់ចាប់ពីម៉ោង ២ រសៀល។ កាហ្វេនៅរានហាល គ្មានកម្មវិធី។ អាហារល្ងាចជាមួយគ្នា រួចវគ្គបើកនៅជុំវិញភ្លើង។" },
        { "whenEn": "Saturday", "whenKm": "ថ្ងៃសៅរ៍", "whatEn": "Free morning — swim, walk, sleep. One guided session after lunch on sustaining ministry without burning out. Free evening.", "whatKm": "ព្រឹកទំនេរ — ហែលទឹក ដើរលេង ឬគេង។ វគ្គណែនាំមួយបន្ទាប់ពីអាហារថ្ងៃត្រង់ ស្តីពីការបម្រើដោយមិនអស់កម្លាំង។ ល្ងាចទំនេរ។" },
        { "whenEn": "Sunday", "whenKm": "ថ្ងៃអាទិត្យ", "whatEn": "Morning worship and a closing conversation. Lunch, then depart in your own time.", "whatKm": "ការគោរពប្រណិប័តន៍ពេលព្រឹក និងការសន្ទនាបិទ។ អាហារថ្ងៃត្រង់ រួចចាកចេញតាមពេលវេលារបស់អ្នក។" }
      ],
      "includesEn": "The fee covers a shared air-conditioned bungalow, all meals, and both guided sessions. Single-occupancy bungalows are available at extra cost — mention it in the notes box when you register.",
      "includesKm": "ថ្លៃសេវារួមបញ្ចូលបន្ទប់ប៊ុងហ្គាឡូម៉ាស៊ីនត្រជាក់រួមគ្នា អាហារទាំងអស់ និងវគ្គណែនាំទាំងពីរ។ បន្ទប់ឯកជនអាចរៀបចំបានដោយបង់ថ្លៃបន្ថែម — សូមសរសេរក្នុងប្រអប់កំណត់ចំណាំពេលចុះឈ្មោះ។",
      "datesEn": "26–28 February 2027",
      "datesKm": "២៦–២៨ កុម្ភៈ ២០២៧",
      "locationEn": "Shalom Valley, Kep",
      "locationKm": "Shalom Valley, កែប",
      "agesEn": "Leaders 18+",
      "agesKm": "អ្នកដឹកនាំ អាយុ ១៨ ឡើង",
      "costEn": "US$95 per person",
      "costKm": "៩៥ ដុល្លារ ក្នុងម្នាក់",
      "deadlineEn": "12 February 2027",
      "deadlineKm": "១២ កុម្ភៈ ២០២៧",
      "fees": [
        { "en": "Shared bungalow (per person, 2 nights)", "km": "ប៊ុងហ្គាឡូរួម (ក្នុងម្នាក់ ២យប់)", "amount": "US$95" },
        { "en": "Private bungalow (per person)", "km": "ប៊ុងហ្គាឡូឯកជន (ក្នុងម្នាក់)", "amount": "US$140" },
        { "en": "Deposit to hold your place", "km": "ប្រាក់កក់ដើម្បីរក្សាកន្លែង", "amount": "US$30" }
      ]
    },

    {
      "slug": "family-camp-2027",
      "status": "open",
      "nameEn": "Shalom Family Camp 2027",
      "nameKm": "ជំរុំគ្រួសារ Shalom ២០២៧",
      "image": "img/poster-family.svg",
      "accent": "#C25E22",
      "accentDark": "#9C4218",
      "accentInk": "#8A3D16",
      "badgeEn": "New this year",
      "badgeKm": "ថ្មីឆ្នាំនេះ",
      "blurbEn": "A long weekend where parents and children play together — pool, beach, bonfire, and no one left on the sidelines.",
      "blurbKm": "ចុងសប្តាហ៍វែងមួយ ដែលឪពុកម្តាយ និងកូនលេងជាមួយគ្នា — អាងហែលទឹក ឆ្នេរ ភ្លើងជំរុំ ហើយគ្មាននរណាម្នាក់ត្រូវទុកចោលឡើយ។",
      "taglineEn": "A weekend for the whole family, together.",
      "taglineKm": "ចុងសប្តាហ៍សម្រាប់គ្រួសារទាំងមូល ជាមួយគ្នា។",
      "purposeEn": "Most camps split families up. This one deliberately does not. Every activity is designed so that a seven-year-old and a forty-year-old can do it side by side, and the programme leaves long gaps for families simply to be together without anywhere to be. Younger children stay with their parents throughout; there is no separate children's programme.",
      "purposeKm": "ជំរុំភាគច្រើនបែងចែកគ្រួសារ។ ជំរុំនេះមិនធ្វើដូច្នេះទេ។ សកម្មភាពទាំងអស់ត្រូវបានរៀបចំឡើងដើម្បីឱ្យកុមារអាយុ ៧ ឆ្នាំ និងមនុស្សអាយុ ៤០ ឆ្នាំ អាចធ្វើជាមួយគ្នាបាន ហើយកម្មវិធីទុកចន្លោះពេលវែង ដើម្បីឱ្យគ្រួសារនៅជាមួយគ្នាដោយគ្មានកន្លែងណាត្រូវទៅ។ កុមារតូចនៅជាមួយឪពុកម្តាយពេញមួយពេល; គ្មានកម្មវិធីដាច់ដោយឡែកសម្រាប់កុមារទេ។",
      "program": [
        { "whenEn": "Friday", "whenKm": "ថ្ងៃសុក្រ", "whatEn": "Arrive and settle into your bungalow. Pool open all afternoon. Welcome dinner and family bonfire.", "whatKm": "មកដល់ និងរៀបចំបន្ទប់ប៊ុងហ្គាឡូ។ អាងហែលទឹកបើកពេញរសៀល។ អាហារល្ងាចស្វាគមន៍ និងភ្លើងជំរុំគ្រួសារ។" },
        { "whenEn": "Saturday", "whenKm": "ថ្ងៃសៅរ៍", "whatEn": "Family team games, salt fields and mangrove walk, afternoon beach trip, bush dance in the evening.", "whatKm": "ល្បែងក្រុមគ្រួសារ ដើរទស្សនាវាលអំបិល និងព្រៃកោងកាង ទៅឆ្នេរពេលរសៀល និងការរាំពេលល្ងាច។" },
        { "whenEn": "Sunday", "whenKm": "ថ្ងៃអាទិត្យ", "whatEn": "Family worship, tree planting together, long lunch, depart when you are ready.", "whatKm": "ការគោរពប្រណិប័តន៍គ្រួសារ ការដាំដើមឈើជាមួយគ្នា អាហារថ្ងៃត្រង់វែង និងចាកចេញពេលអ្នកត្រៀមរួច។" }
      ],
      "includesEn": "The fee covers your family bungalow, all meals, and every activity including the beach trip. Children under 4 stay and eat free. Tell us any food allergies in the notes box — the kitchen can cook Khmer or Western menus.",
      "includesKm": "ថ្លៃសេវារួមបញ្ចូលបន្ទប់ប៊ុងហ្គាឡូគ្រួសារ អាហារទាំងអស់ និងសកម្មភាពទាំងអស់រួមទាំងការទៅឆ្នេរ។ កុមារអាយុក្រោម ៤ ឆ្នាំស្នាក់នៅ និងបរិភោគដោយឥតគិតថ្លៃ។ សូមប្រាប់យើងអំពីអាឡែស៊ីអាហារក្នុងប្រអប់កំណត់ចំណាំ — ផ្ទះបាយអាចចម្អិនម្ហូបខ្មែរ ឬបស្ចិមប្រទេស។",
      "datesEn": "16–18 April 2027",
      "datesKm": "១៦–១៨ មេសា ២០២៧",
      "locationEn": "Shalom Valley, Kep",
      "locationKm": "Shalom Valley, កែប",
      "agesEn": "All ages welcome",
      "agesKm": "ស្វាគមន៍គ្រប់វ័យ",
      "costEn": "US$60 per bungalow per night",
      "costKm": "៦០ ដុល្លារ ក្នុងមួយបន្ទប់ក្នុងមួយយប់",
      "deadlineEn": "31 March 2027",
      "deadlineKm": "៣១ មីនា ២០២៧",
      "fees": [
        { "en": "Family bungalow (per night, up to 4)", "km": "ប៊ុងហ្គាឡូគ្រួសារ (ក្នុងមួយយប់ ដល់ ៤នាក់)", "amount": "US$60" },
        { "en": "Larger bungalow (per night, up to 6)", "km": "ប៊ុងហ្គាឡូធំ (ក្នុងមួយយប់ ដល់ ៦នាក់)", "amount": "US$90" },
        { "en": "Meals (per person per day)", "km": "អាហារ (ក្នុងម្នាក់ក្នុងមួយថ្ងៃ)", "amount": "US$15" },
        { "en": "Children under 4", "km": "កុមារអាយុក្រោម ៤ ឆ្នាំ", "amount": "Free" },
        { "en": "Deposit to hold your bungalow", "km": "ប្រាក់កក់ដើម្បីរក្សាបន្ទប់", "amount": "US$40" }
      ]
    }

  ]
};
